# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'SW-sdk-NetStandard.sln'
    feedsToUse: 'config'
    nugetConfigPath: 'NuGet.config'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'SW-sdk-NetStandard.sln'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'test/sdk-test/sdk-test.csproj'
    publishTestResults: false
    workingDirectory: 'test/sdk-test'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    projects: 'src/sw-sdk/*.csproj'
    custom: 'pack'
    arguments: '--version-suffix rc'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'src/sw-sdk/bin'
    ArtifactName: 'bin'
    publishLocation: 'Container'
